version: "2"
services:
    db:
        image: mysql:5.7
        volumes:
            - ./mysql/init:/docker-entrypoint-initdb.d
            - "./mysql/mysql_conf/my.cnf:/etc/mysql/my.cnf"
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: pyGiCgyvIxgpn2h4
    nodejs:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile-nodejs
        restart: always
        depends_on:
            - db
        image: yadayuki/node-web-app
        ports: 
            - "3000:3000" 
        hostname: 
            node
        environment: 
            DB_HOST: db
        volumes:
            - ./log:/usr/src/node_docker/log
    nginx_server:
        build: 
            context: .
            dockerfile: ./dockerfiles/Dockerfile-nginx
        depends_on: 
            - nodejs
        restart: always
        image: nginx-webserver
        ports: 
            - "80:80"
