x-aws-vpc: "vpc-090139b1c2a524f73"

version: "2"
services:
    db:
        image: 955847467435.dkr.ecr.ap-northeast-1.amazonaws.com/effectivest/database:latest
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile-mysql
        restart: always
        env_file:
            - ./.env
        ports: 
            - "3306:3306"
    nodejs:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile-nodejs
        restart: always
        depends_on:
            - db
        image: 955847467435.dkr.ecr.ap-northeast-1.amazonaws.com/effectivest/server:latest
        ports: 
            - "3000:3000" 
        hostname: 
            node
        environment: 
            DB_HOST: db
    nginx_server:
        build: 
            context: .
            dockerfile: ./dockerfiles/Dockerfile-nginx
        depends_on: 
            - nodejs
        restart: always
        image: 955847467435.dkr.ecr.ap-northeast-1.amazonaws.com/effectivest/proxy:latest
        ports: 
            - "80:80"
